# Generated by Django 4.2.5 on 2023-10-08 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.category'),
        ),
    ]
