# Generated by Django 4.2.5 on 2023-10-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_course_track'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='track',
            new_name='categ',
        ),
    ]
