# Generated by Django 4.2.5 on 2023-10-08 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_rename_track_course_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='categ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='homepage.category'),
        ),
    ]
